name: flutter_mobigate
description: Flutter Mobigate SDK plugin. MobigateSDK is a tool for gathering users phone data and events tracking.
version: 1.0.2
homepage: https://wiki.spicymobile.pl/wiki/mobigatesdk

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pl.spicymobile.flutter_mobigate
        pluginClass: FlutterMobigatePlugin